version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
      - npm update

  pre_build:
    commands:
      - echo Fetching appconstants.txt from S3...
      - aws s3 cp s3://your-bucket/path/to/appconstants.txt /path/to/your/app/appconstants.txt

  build:
    commands:
      - echo Building the application...
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no

cache:
  paths:
    - node_modules/**/*
