version: 0.2

phases:
  install:

    commands:
      - npm install
  pre_build:
    commands:
      - echo "Starting the build phase..."
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'  # include all files in the build artifacts
