version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
      - npm update


  build:
    commands:
      - echo Building the application...
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no

cache:
  paths:
    - node_modules/**/*
