version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the application...
      - npm run build

artifacts:
  files:
    - '**/*'  # This includes all files and directories
  discard-paths: no  # Retains the full directory structure

cache:
  paths:
    - node_modules/**/*
